---
# Genie role
- name: Copy local Genie WAR file {{ local_war }}
  copy: src={{ local_war }} dest=/usr/local/tomcat/webapps/genie.war
  when: local_war != ""
  tags: deploy
  
- name: Download snapshot build of Genie from Cloudbees
  get_url: url={{ latest_successful_build_url }} dest=/usr/local/tomcat/webapps/genie.war
  when: local_war == ""
  tags: deploy
  
