---
ami_build: ami is defined and ami 
not_ami_build: ami is not defined or not ami
latest_successful_build_url: https://netflixoss.ci.cloudbees.com/job/SimianArmy-master/lastSuccessfulBuild/artifact/build/libs/simianarmy-2.4-SNAPSHOT.war