---
# Asgard playbook for Amazon Linux
- name: Asgard
  user: ec2-user
  sudo: True
  tags: asgard
  hosts: all
  roles:
    - base
    - tomcat
    - asgard
  vars:
    local_war: "" 
    tomcat_extra_opts: "-Darchaius.deployment.applicationId=asgard -Dnetflix.datacenter=cloud"
  vars_files:
    - vars/{{ ansible_distribution }}.yml
  
