---
# Genie playbook for ubuntu
- name: Genie
  user: ubuntu
  sudo: True
  tags: genie
  hosts: all
  roles:
    - base
    - tomcat
    - genie
  vars:
    local_war: "" 
  vars_files:
    - vars/$ansible_distribution.yml
